import { Routes } from '@angular/router';
import { HomeComponent } from './instructor/home/home.component';
import { StudentsComponent } from './instructor/students/students.component';
import { ResultComponent } from './instructor/result/result.component';
import { ProfileInstComponent } from './instructor/profile-inst/profile-inst.component';
import { ResponseReviewComponent } from './instructor/response-review/response-review.component';
import { StudentAssessmentsComponent } from './instructor/student-assessments/student-assessments.component';
import { ManageComponent } from './instructor/manage/manage.component';
import { CoordinatorComponent } from './instructor/coordinator/coordinator.component';
import { EvaluateComponent } from './instructor/evaluate/evaluate.component';
import { MasteryResultComponent } from './instructor/mastery-result/mastery-result.component';
import { AssignAssessmentComponent } from './instructor/assign-assessment/assign-assessment.component';
import { FinalGenerateAssessmentComponent } from './instructor/final-generate-assessment/final-generate-assessment.component';
import { EditAssessmentComponent } from './instructor/edit-assessment/edit-assessment.component';
import { StudentAttemptComponent } from './instructor/student-attempt/student-attempt.component';
import { ArchiveComponent } from './instructor/archive/archive.component';
import { AssessmentSettingsComponent } from './instructor/assessment-settings/assessment-settings.component';
import { AnalyticsComponent } from './instructor/analytics/analytics.component';

export const INSTRUCTOR_ROUTES: Routes = [
    { path: 'dashboard', component: HomeComponent },
    { path: 'students', component: StudentsComponent },
    { path: 'profile', component: ProfileInstComponent },
    { path: 'createAssessment', component: FinalGenerateAssessmentComponent },
    { path: 'assign', component: AssignAssessmentComponent },
    { path: 'result', component: ResultComponent },
    { path: 'result/mastery', component: MasteryResultComponent },
    { path: 'coordinator', component: CoordinatorComponent },
    { path: 'evaluate', component: EvaluateComponent },
    { path: 'response', component: ResponseReviewComponent },
    { path: 'analytics', component: AnalyticsComponent },
    { path: 'students/assessments', component: StudentAssessmentsComponent },
    { path: 'edit', component: EditAssessmentComponent },
    { path: 'manage', component: ManageComponent },
    { path: 'response/attempts', component: StudentAttemptComponent },
    { path: 'archives', component: ArchiveComponent },
    { path: 'result/settings', component: AssessmentSettingsComponent },
]; 